---
- hosts: all
  become: true
  tasks:

  - name: install python3 and pip3
    apt:
     name:
          - python3
          - python3-pip

     state: present

  - name: installing java
    apt:
     name: default-jdk

     state: present
  - name: setting default python
    command: update-alternatives --install usr/bin/python python usr/bin/python3

  - name: setting default pip3
    command: update-alternatives --install /usr/bin/python/pip pip /usr/bin/pip3

  



